### ISSUE TITLE
Potential issue with adaptive banner

### ISSUE THREAD

**Issue by Dragosha** [defold/extension-admob#9] opened 2021-05-19 12:43 UTC
On user' device adaptive banner with BOTTOM_CENTER position shows as a big banner that occupies whole screen (see screenshot).
admob.show_banner(admob.POS_BOTTOM_CENTER)

Device:
Motorola one power (Screen size 1080x2246) Android version: Android 9 (SDK 28)

![Screenshot_20210516-202304](https://user-images.githubusercontent.com/842807/118813108-3fe6ea80-b8c8-11eb-81e0-04188cfa0f2f.png)

**Comment by AGulev** [comment] 2021-07-24 08:12
Thx for the report. I'll update SDK and try to use the new API for the adaptive banner they introduced in the new version.

**Comment by AGulev** [comment] 2023-11-07 16:54
@Dragosha I'm closing this issue because I assume it fixed since using (we already use newer API). Let me know if you'll be able to reproduce something like that.

**Closed by AGulev** 2023-11-07 16:54 UTC
